version: '3.1'
services:
  
  # frontend:
    # image: ""
    # restart: always

    # depends_on:
    #   - nginx
    #   - mongodb
    #   - fast_api
    #   - rabbit_mq
    #   - crawler

    # networks:

    # environment:

  nginx:
    image: ""
    restart: always

    depends_on:
      - mongodb
      - fast_api
      - rabbit_mq
      - crawler

    networks:

    environment:

  rabbit_mq:
    image: 
    restart: always
    networks:

    depends_on:
      - mongodb

    environment:

  fast_api:
    image: ""
    restart: always

    depends_on:
      - mongodb

    networks:

    environment:

  crawler:
    image: ""
    restart: always
    networks:

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

# Use root/example as user/password credentials

# mongo-express:
#   image: mongo-express
#   restart: always
#   ports:
#     - 8081:8081
#   environment:
#     ME_CONFIG_MONGODB_ADMINUSERNAME: root
#     ME_CONFIG_MONGODB_ADMINPASSWORD: example
#     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/